---
name: Compile Unix Library (arm64)

description: |
  Prepare and compile unix builds for arm64 cpus

inputs:
  compiler:
    required: true
    description: Compiler to use
  distro:
    required: false
    description: the base os to run in arm64 mode
    default: ubuntu20-04

runs:
  using: composite
  steps:

    - name: Compile
      uses: ./.github/actions/run-on-linux-aarch64
      with:
        distro: ${{ inputs.distro }}
        compiler: ${{ inputs.compiler }}
        run: make test

