---
name: Prepare artifacts

description: |
  Downloads all prior artifacts into a directory.

  each artifact will be in its own directory named after the
  job that uploaded it.

outputs:
  staging_area:
      description: Area in which artifacts from prior jobs are collated
      value: ${{ steps.staging_area.outputs.value }}

runs:
  using: composite
  steps:

    - name: Prepare Staging Area
      shell: bash
      id: staging_area
      run: |
        STAGING=$(mktemp -d)
        echo "value=${STAGING}" >> $GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        path: ${{ steps.staging_area.outputs.value }}

    - name: Prepare Release
      env:
        STAGING: ${{ steps.staging_area.outputs.value }}
      shell: bash
      run: |

        mkdir -p ${STAGING}
        for file in ${SOURCE}/**/*; do
          FILENAME=$(basename $file)
          PLATFORM=$(basename $(dirname $file))
          cp $file "${STAGING}/${PLATFORM}-${FILENAME}"
        done

        ls -al ${STAGING}/*

