---
name: Execute on linux aarch64 cpu

description: |
  Spins up a qemu vm in a container to execute provided commands in a aarch64 cpu 

inputs:
  compiler:
    required: true
    description: Compiler to use
  dockerimage:
    required: false
    description: "the base os image to run in arm64 mode. see https://github.com/uraimo/run-on-arch-action#supported-platforms"
    default: ubuntu20-04
  run:
    required: false
    description: the cmd to run
    default: make
  setup:
    required: false
    description: the host setup cmd to run

runs:
  using: composite
  steps:

    - name: Prepare
      uses: uraimo/run-on-arch-action@v2.5.0
      # see: https://github.com/uraimo/run-on-arch-action#usage
      with:
        arch: aarch64
        distro: ${{ inputs.dockerimage }}
        
        # Create an artifacts directory
        setup: |
          mkdir -p "${PWD}/artifacts"

        # Mount the artifacts directory as /artifacts in the container
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"

        env: |
          CC: ${{ inputs.compiler }}
          LD_LIBRARY_PATH: /usr/lib:/usr/local/lib
          RUN: ${{ inputs.run }}
          ${{ inputs.env }}

        install: |
          case "${{ inputs.dockerimage }}" in
            ubuntu*|jessie|stretch|buster)
              apt update -q -y
              apt install -q -y build-essential git
              ;;
          esac

        run: |
          cc --version

          git clone https://github.com/Conni2461/examiner;
          
          cd examiner;
          make && sudo make install;
          cd ..

          ${{env.RUN}}

