---
name: Test unix library

description: |
  Compile and test a unix build

inputs:
  compiler:
    required: true
    description: Compiler to use


runs:
  using: composite
  steps:
    - uses: .github/actions/compile-unix
      with:
        compiler: ${{ inputs.compiler }}

    - name: Tests
      env:
        CC: ${{ inputs.compiler }}
        LD_LIBRARY_PATH: /usr/lib:/usr/local/lib
      shell: bash
      run: make test

