---
description: |
  Prepare and compile a windows build

steps:
  - uses: lukka/get-cmake@latest

  - name: Build
    run: |
      cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
      cmake --build build --config Release
      cmake --install build --prefix build

