name: CI

on: [push, pull_request]

jobs:
  gcc:
    name: c build and tests
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            compiler: gcc
          - os: ubuntu-20.04
            compiler: clang
          - os: macos-10.15
            compiler: gcc
          - os: macos-10.15
            compiler: clang

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.gitub/actions/test-unix
        with:
          compiler: ${{ matrix.compiler }}

  windows:
    name: windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/compile-windows

  nvim-tests:
    name: nvim-tests
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        include:
          - os: ubuntu-20.04
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          - os: macos-10.15
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/nvim-unix-test
        with:
          os: ${{ matrix.os }}
          url: ${{ matrix.url }}

