name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  unittest_linux_x86_64:
    name: unittest-linux-x86_64
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc
          - os: ubuntu-22.04
            compiler: clang

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/unittest-unix-x86_64
        with:
          compiler: ${{ matrix.compiler }}

  unittest_linux_arm64:
    name: unittest-linux-arm64
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc
          - os: ubuntu-22.04
            compiler: clang

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/unittest-unix-arm64
        with:
          compiler: ${{ matrix.compiler }}
          distro:  ${{ matrix.os }}

  unittest_macosx_x86_64:
    name: unittests-macosx-x86_64
    strategy:
      matrix:
        include:
          - os: macos-12
            compiler: gcc
          - os: macos-12
            compiler: clang

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/unittest-unix-x86_64
        with:
          compiler: ${{ matrix.compiler }}

  unittest_windows_x86_64:
    name: unittest-windows-x86_64
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/compile-windows-x86_64

  e2etest_linux_x86_64:
    name: e2etest-linux-x86_64
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/e2etest-unix-x86_64
        with:
          os: ${{ matrix.os }}
          url: ${{ matrix.url }}

  e2etest_macos_x86_64:
    name: e2etest-macos-x86_64
    strategy:
      matrix:
        include:
          - os: macos-10.15
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/e2etest-unix-x86_64
        with:
          os: ${{ matrix.os }}
          url: ${{ matrix.url }}

