name: Linting and style checking

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  luacheck:
    name: Lint/luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: make lint

  clangformat:
    name: Lint/clangformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format
      - name: Format
        run: make format

  stylua:
    name: Lint/stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check lua/
