name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unix:
    name: unix build

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            compiler: gcc
          - os: ubuntu-20.04
            compiler: clang
          - os: macos-10.15
            compiler: gcc
          - os: macos-10.15
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3


      - uses: ./.github/actions/compile-unix
        with:
          compiler: ${{ matrix.compiler }}


      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{matrix.compiler}}
          path: build/*.so

  windows:
    name: windows build

    strategy:
      matrix:
        include:
          # TODO: add in clang build too ?
          - os: windows-2019
            # TODO: specify actual correct compiler name here for windows
            compiler: cc

    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - uses: ./.github/actions/compile-windows

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}
          path: build/*.dll

  release:
    needs:
      - windows
      - unix

    name: Release binaries

    runs-on: ubuntu-latest
      
    steps:

      - uses: actions/checkout@v3

      - name: Download artifact
        id: artifacts
        uses: ./.github/actions/prepare-artifacts

      - uses: ./.github/actions/release-binaries
        with:
          source: ${{ steps.artifact.outputs.staging_area }}
          is_development_release: ${{ github.ref_name == 'main' }}
          is_production_release: ${{ startsWith(github.ref, 'refs/tags') }}
          development_tag: dev
          development_title: "dev (unstable)"
          production_tag: ${{ github.ref_name }} # if we only consider tagged runs to be prod, then this will be the tag name
          production_title: "Release: ${{ github.ref_name }}"

