name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux_x86_64:
    name: make-linux-binaries

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            compiler: gcc
          - os: ubuntu-22.04
            platform: linux
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: ./.github/actions/compile-unix-x86_64
        with:
          compiler: ${{ matrix.compiler }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-x86_64-${{ matrix.compiler }}
          path: build/*.so

  linux_arm64:
    name: make-linux-binaries

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            compiler: gcc
          - os: ubuntu-22.04
            platform: linux
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: ./.github/actions/compile-unix-arm64
        with:
          compiler: ${{ matrix.compiler }}
          distro: ${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-arm64-${{ matrix.compiler }}
          path: build/*.so

  macos_x86_64:
    name: make-macos-binaries

    strategy:
      matrix:
        include:
          - os: macos-12
            platform: macos
            compiler: gcc
          - os: macos-12
            platform: macos
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: ./.github/actions/compile-unix-x86_64
        with:
          compiler: ${{ matrix.compiler }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-x86_64-${{ matrix.compiler }}
          path: build/*.so

  windows_x86_64:
    name: make-windows-binaries

    strategy:
      matrix:
        include:
          # TODO: add in clang build too ?
          - os: windows-2019
            platform: win32
            compiler: cc

    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3

      - uses: ./.github/actions/compile-windows-x86_64

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-x86_64-${{ matrix.compiler }}
          path: build/*.dll

  release:
    needs:
      - linux_x86_64
      - linux_arm64
      - macos_x86_64
      - windows_x86_64

    name: upload-binaries-to-release-page

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Download artifacts from previous jobs
        id: artifacts
        uses: ./.github/actions/prepare-artifacts

      - name: Upload release binaries
        uses: ./.github/actions/release-binaries
        with:
          source: ${{ steps.artifacts.outputs.staging_area }}
          is_development_release: ${{ !startsWith(github.ref, 'refs/tags') }}
          is_production_release: ${{ startsWith(github.ref, 'refs/tags') }}
          development_tag: dev
          development_title: "dev (unstable)"
          production_tag: ${{ github.ref_name }} # if we only consider tagged runs to be prod, then this will be the tag name
          production_title: "Release: ${{ github.ref_name }}"
